import "./globals.css";
import Link from "next/link";
import { Metadata } from "next";
import getUser from "./actions/get-user";
import Login from "@/components/LoggInner";
import SelectNav from "@/components/SelectNav";
import { ThemeProvider } from "@teispace/next-themes";
import { getTheme } from "@teispace/next-themes/server";
import Script from "next/script";

// export const metadata: Metadata = {
//   title: "Taksh",
//   description: "Generated by create next app",
//   icons: "/logo.png?v=2"
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialTheme = await getTheme();

  const user = await getUser();

  const authButton = !!user ? (
    <Link href="/">
      <button className="bg-transparent rounded-lg text-sm px-3 py-1.5 border border-gray-200 text-white">
        Dashboard
      </button>
    </Link>
  ) : (
    <div className="flex items-center gap-3">
      <Link
        href="/auth/sign-in"
        className="text-sm font-medium text-zinc-300 hover:text-white"
      >
        Sign In
      </Link>
      <Link
        href="/auth/sign-up"
        className="rounded-xl bg-orange-500 px-4 py-2 text-sm font-medium text-white hover:bg-orange-400"
      >
        Get Started
      </Link>
    </div>
  );

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="icon"
          type="image/png"
          href="/favicon-96x96.png?v=20260621"
          sizes="96x96"
        />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg?v=20260621" />
        <link rel="shortcut icon" href="/favicon.ico?v=20260621" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png?v=20260621"
        />
        <meta name="apple-mobile-web-app-title" content="Taksh" />
        <link rel="manifest" href="/site.webmanifest?v=20260621" />
      </head>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* @ts-ignore */}
          <Login user={user} />
          {/* @ts-ignore */}
          <SelectNav authButton={authButton} user={user} />
          <div className="pt-14">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
